[project]
name = "donsker"
version = "0.1.0"
description = "Simulations for talk on Donsker's Theorem"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "scipy>=1.15.2",
]
